### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by JS-Sensei** [bahmutov/cypress-failed-log#24] opened 2018-06-21 13:36 UTC
I added cypress-failed-log to my project and for some reason i get the following error: `TypeError: Converting circular structure to JSON`. Here is a reproducible code: 
```js
describe('error code for cypress failed log issue', () => {
   it('should produce an TypeError: Converting circular structure to JSON ', () => {
      cy.visit('xxxx.html'); 
      cy.wrap([
         '[data-test-id="login-user-name"]',
         '[data-test-id="login-user-pwd"]',
         '[data-test-id="login-button"]'
      ]).each( selector => {
         cy.get(selector, { timeout: 30000 } ).should('be.visible');
      });
      /* [
         '[data-test-id="login-user-name"]',
         '[data-test-id="login-user-pwd"]',
         '[data-test-id="login-button"]'
      ].forEach(selector => {
         cy.get(selector, { timeout: 30000 } ).should('be.visible');
      }); */
   });
});

```
Obviously  you have to replace the url *xxxx.html*  that should point to a webpage having elements with the data-test-id attribute set as those in the array.  Here is a screenshot of the test runner after I ran the test code up there: 

![cypress-failed-log-error](https://user-images.githubusercontent.com/26506216/41722405-be420762-7568-11e8-9f92-ce63d4397520.png)

**Comment by bahmutov** [comment] 2018-06-21 13:47
Thanks for opening the issue! Can you make an HTML file with these properties (and that fails to log) please? Otherwise it will be: I made a file, serve it but cannot reproduce it

**Comment by JS-Sensei** [comment] 2018-06-21 14:09
Hi, I quickly came up with this html file
```html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Cypress Failed Log Issue</title>
</head>
<body>
   <input type="text" data-test-id="login-user-name">
   <input type="text" data-test-id="login-user-pwd">
   <button data-test-id="login-button">Login</button>
</body>
</html>

```

I served it using live server(from vs code) and run the test again and it works...

![screenshot_2018-06-21_16-08-54](https://user-images.githubusercontent.com/26506216/41724246-6e8c4886-756d-11e8-9cbc-249806b6b30d.png)

**Comment by bahmutov** [comment] 2018-06-21 14:20
exactly, so if I don't have a reproducible example ... it will be hard for me to hunt to the root cause of the bug

**Comment by kkor** [comment] 2018-07-30 07:44
I also ran into this issue, a successful test case started failing when I added cypress-failed-log (at a ` cy.get('.classname, { timeout: 10000 });`).
The logs are just a nice-to.have addition, so did not investigate further or reproduce in a shareable setting.

**Comment by llatinov** [comment] 2018-08-15 07:26
I think the problem comes from `{ timeout: 10000 }`, if you try the same test only with `cy.get('.classname')` it will work, but if you add some config to the command then it fails `cy.get('.classname', {})`

**Comment by aurelijusbanelis** [comment] 2018-08-23 08:47
Have same issue with `{timeout: 3000}`

Tested with:
```json
  "devDependencies": {
    "cypress": "^3.1.0",
    "cypress-failed-log": "git@github.com:llatinov/cypress-failed-log.git#master"
  }
```
It fixes the issue.

It would be good to have https://github.com/llatinov/cypress-failed-log/commit/b16c8f6b17f3ac3079854ba41df38ac1f680d7bd reviewed/merged.
And have fully working/stable version in `npm`.

**Closed as completed** 2018-10-10 14:24 UTC
Labels: bug
